-- AlterTable
ALTER TABLE `Space` MODIFY `imageUrl` VARCHAR(1000) NULL,
    MODIFY `isPublic` VARCHAR(4) NULL DEFAULT 'Y',
    MODIFY `registedAt` TIMESTAMP(0) NULL,
    MODIFY `createdAt` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0);
